DNAAS-LEAF-A01:
- network-services bridge-domain instance g_demo_v400 interface bundle-3195.400
- interfaces bundle-3195.400 l2-service enabled
- interfaces bundle-3195.400 vlan-id 400
- network-services bridge-domain instance g_demo_v400 interface ge100-0/0/10.400
- interfaces ge100-0/0/10.400 l2-service enabled
- interfaces ge100-0/0/10.400 vlan-id 400
DNAAS-LEAF-A02:
- network-services bridge-domain instance g_demo_v400 interface bundle-60413.400
- interfaces bundle-60413.400 l2-service enabled
- interfaces bundle-60413.400 vlan-id 400
- network-services bridge-domain instance g_demo_v400 interface ge100-0/0/20.400
- interfaces ge100-0/0/20.400 l2-service enabled
- interfaces ge100-0/0/20.400 vlan-id 400
DNAAS-LEAF-A03:
- network-services bridge-domain instance g_demo_v400 interface bundle-60413.400
- interfaces bundle-60413.400 l2-service enabled
- interfaces bundle-60413.400 vlan-id 400
- network-services bridge-domain instance g_demo_v400 interface ge100-0/0/30.400
- interfaces ge100-0/0/30.400 l2-service enabled
- interfaces ge100-0/0/30.400 vlan-id 400
DNAAS-SPINE-A08:
- network-services bridge-domain instance g_demo_v400 interface bundle-3195.400
- interfaces bundle-3195.400 l2-service enabled
- interfaces bundle-3195.400 vlan-id 400
- network-services bridge-domain instance g_demo_v400 interface bundle-60413.400
- interfaces bundle-60413.400 l2-service enabled
- interfaces bundle-60413.400 vlan-id 400
